import Header from "../Header"
import Footer from "../Footer"
import Head from 'next/head'

export default function Layout({ children }) {
    return <>
        <head>
            <title>Imperial</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <script src="https://kit.fontawesome.com/5b73c335af.js" 
            crossorigin="anonymous"></script>
        </head>
        <Header />
        <main>
            {children}
        </main>
        <Footer />
    </>

}